<?php
include "header.php";
?>

<div class="container">

	<div class="row">

		<div class="col-lg-9">
			
			<h1>Terms of Use</a></h1>

			<hr>

			<p>BY USING THE SITE, YOU AGREE TO THESE TERMS OF USE; IF YOU DO NOT AGREE TO ANY AND ALL OF THESE TERMS, DO NOT USE THE SITE.</p>

			<p>These Terms and Conditions of Use (the “Terms of Use”) apply to the Romine Enterprises, LLC d/b/a color-my-i (“Romine Enterprises, LLC”) web site located at www.color-my-i.com (the “Site”), and all associated sites linked to the Site by Romine Enterprises, LLC, its agents, licensees, subsidiaries, or affiliates. The Site is the property of Romine Enterprises, LLC. Romine Enterprises, LLC reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time. It is your responsibility to check these Terms of Use periodically for changes. Your continued use of the Site following the posting of changes will mean that you accept and agree to the changes. As long as you comply with these Terms of Use, Romine Enterprises, LLC grants you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Site.</p>

			<p>www.color-my-i.com, color-my-i, and the color-my-i logo are trademarks and/or service marks of Romine Enterprises, LLC. All phones are professionally refurbished and/or modified—they are not brand new. Custom front and back housings are not produced or installed by Apple, Inc. "Apple," "iPhone," "MacBook" and the Apple logo are trademarks of Apple, Inc. THIS SITE, COLOR-MY-I, AND ROMINE ENTERPRISES, LLC, ARE NOT AFFILIATED WITH OR ENDORSED BY APPLE, INC. OR ANY OF ITS SUBSIDIARIES OR AFFILIATES. All custom artwork, etching, design, and modification of any kind offered by color-my-i is the exclusive intellectual property of Romine Enterprises, LLC.</p>

			<p>All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, artwork and computer code (collectively, “Content”), including but not limited to the design, structure, selection, coordination, expression, “look and feel” and arrangement of such Content, contained on the Site is owned, controlled or licensed by Romine Enterprises, LLC, and is protected by copyright laws, trademark laws, and various other intellectual property rights and unfair competition laws.</p>

			<p>Except as expressly provided in these Terms of Use, no part of the Site and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including “mirroring”) to any other computer, server, Web site or other medium for publication or distribution or for any commercial enterprise, without Romine Enterprises, LLC’s express prior written consent.</p>
			<p>You may not use any automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Site or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Site or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Site. Romine Enterprises, LLC reserves the right to bar any such activity.</p>

			<p>You may not attempt to gain unauthorized access to any portion or feature of the Site, or any other systems or networks connected to the Site or to any Romine Enterprises, LLC server, or to any of the services offered on or through the Site.</p>

			<p>You may not probe, scan or test the vulnerability of the Site or any network connected to the Site, nor breach the security or authentication measures on the Site or any network connected to the Site. You may not reverse look-up, trace or seek to trace any information on any other user of or visitor to the Site, or any other customer of Romine Enterprises, LLC to its source, or exploit the Site or any service or information made available or offered by or through the Site, in any way where the purpose is to reveal any information, including but not limited to personal identification or information.</p>

			<p>You agree that you will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Site or Romine Enterprises, LLC’s systems or networks, or any systems or networks connected to the Site or to Romine Enterprises, LLC.</p>

			<p>You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Site or any transaction being conducted on the Site, or with any other person’s use of the Site.</p>

			<p>You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal you send to Romine Enterprises, LLC on or through the Site or any service offered on or through the Site. You may not pretend that you are, or that you represent, someone else, or impersonate any other individual or entity.</p>

			<p>You may not use the Site or any Content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of Romine Enterprises, LLC.</p>

			<p>Romine Enterprises, LLC may make changes to any products or services offered on the Site, or to the applicable prices for any such products or services, at any time, without notice. The materials on the Site with respect to products and services may be out of date, and Romine Enterprises, LLC makes no commitment to update the materials on the Site with respect to such products and services.</p>

			<p>You acknowledge and agree that Internet transmissions are never completely private or secure. You understand that any message or information you send to the Site may be read or intercepted by others, even if there is a special notice that a particular transmission (for example, credit card information) is encrypted.</p>

			<p>This Site may contain links to other independent third-party Web sites (“Linked Sites”). These Linked Sites are provided solely as a convenience to our visitors. Such Linked Sites are not under Romine Enterprises, LLC’s control, and Romine Enterprises, LLC is not responsible for and does not endorse the content of such Linked Sites, including any information or materials contained on such Linked Sites. You will need to make your own independent judgment regarding your interaction with these Linked Sites.</p>

			<p>ROMINE ENTERPRISES, LLC DOES NOT PROMISE THAT THE SITE OR ANY CONTENT, SERVICE OR FEATURE OF THE SITE WILL BE ERROR-FREE OR UNINTERRUPTED, OR THAT ANY DEFECTS WILL BE CORRECTED, OR THAT YOUR USE OF THE SITE WILL PROVIDE SPECIFIC RESULTS. THE SITE AND ITS CONTENT ARE DELIVERED ON AN “AS-IS” AND “AS-AVAILABLE” BASIS. ALL INFORMATION PROVIDED ON THE SITE IS SUBJECT TO CHANGE WITHOUT NOTICE. ROMINE ENTERPRISES, LLC DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING ANY WARRANTIES OF ACCURACY, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. ROMINE ENTERPRISES, LLC DISCLAIMS ANY AND ALL LIABILITY FOR THE ACTS, OMISSIONS AND CONDUCT OF ANY THIRD PARTIES IN CONNECTION WITH OR RELATED TO YOUR USE OF THE SITE AND/OR ANY ROMINE ENTERPRISES, LLC SERVICES. YOU ASSUME TOTAL RESPONSIBILITY FOR YOUR USE OF THE SITE AND ANY LINKED SITES. YOUR SOLE REMEDY AGAINST ROMINE ENTERPRISES, LLC FOR DISSATISFACTION WITH THE SITE OR ANY CONTENT IS TO STOP USING THE SITE OR ANY SUCH CONTENT. THIS LIMITATION OF RELIEF IS A PART OF THE BARGAIN BETWEEN THE PARTIES.</p>

			<p>Romine Enterprises, LLC reserves the right to do any of the following, at any time, without notice: (1) to modify, suspend or terminate operation of or access to the Site, or any portion of the Site, for any reason; (2) to modify or change the Site, or any portion of the Site, and any applicable policies or terms; and (3) to interrupt the operation of the Site, or any portion of the Site, as necessary to perform routine or non-routine maintenance, error correction, or other changes.</p>

			<p>Except where prohibited by law, in no event will Romine Enterprises, LLC be liable to you for any indirect, consequential, exemplary, incidental or punitive damages, including lost profits, even if Romine Enterprises, LLC has been advised of the possibility of such damages.</p>

			<p>If, notwithstanding the other provisions of these Terms of Use, Romine Enterprises, LLC is found to be liable to you for any damage or loss which arises out of or is in any way connected with your use of the Site or any Content, Romine Enterprises, LLC’s liability shall in no event exceed One Hundred and 00/100 dollars ($100.00).</p>

			<p>You agree to indemnify and hold Romine Enterprises, LLC, its officers, directors, shareholders, predecessors, successors in interest, employees, agents, subsidiaries and affiliates, harmless from any demands, loss, liability, claims or expenses (including attorneys’ fees), made against Romine Enterprises, LLC by any third party due to or arising out of or in connection with your use of the Site.</p>

			<p>Romine Enterprises, LLC may disclose any information we have about you (including your identity) if we determine that such disclosure is necessary in connection with any investigation or complaint regarding your use of the Site, or to identify, contact or bring legal action against someone who may be causing injury to or interference with (either intentionally or unintentionally) Romine Enterprises, LLC’s rights or property, or the rights or property of visitors to or users of the Site, including Romine Enterprises, LLC’s customers. Romine Enterprises, LLC reserves the right at all times to disclose any information that Romine Enterprises, LLC deems necessary to comply with any applicable law, regulation, legal process or governmental request.</p>

			<p>You acknowledge and agree that Romine Enterprises, LLC may preserve any transmittal or communication by you with Romine Enterprises, LLC through the Site or any service offered on or through the Site, and may disclose such data if Romine Enterprises, LLC determines that such preservation or disclosure is reasonably necessary to (1) comply with legal process, (2) enforce these Terms of Use, (3) respond to claims that any such data violates the rights of others, or (4) protect the rights, property or personal safety of Romine Enterprises, LLC, its employees, users of or visitors to the Site, and the public.</p>

			<p>You agree that Romine Enterprises, LLC may, in its sole discretion and without prior notice, terminate your access to the Site and/or block your future access to the Site if we determine that you have violated these Terms of Use or other agreements or guidelines which may be associated with your use of the Site. You also agree that any violation by you of these Terms of Use will constitute an unlawful and unfair business practice, and will cause irreparable harm to Romine Enterprises, LLC, for which monetary damages would be inadequate, and you consent to Romine Enterprises, LLC obtaining any injunctive or equitable relief that Romine Enterprises, LLC deems necessary or appropriate in such circumstances. These remedies are in addition to any other remedies Romine Enterprises, LLC may have at law or in equity.</p>

			<p>You agree that Romine Enterprises, LLC may, in its sole discretion and without prior notice, terminate your access to the Site.</p>

			<p>If Romine Enterprises, LLC does take any legal action against you as a result of your violation of these Terms of Use, Romine Enterprises, LLC will be entitled to recover from you, and you agree to pay, all reasonable attorneys’ fees and costs of such action, in addition to any other relief granted to Romine Enterprises, LLC. You agree that Romine Enterprises, LLC will not be liable to you or to any third party for termination of your access to the Site as a result of any violation of these Terms of Use.</p>

			<p>You agree that all matters relating to your access to or use of the Site, including all disputes arising therefrom or in any way pertaining thereto, will be governed by the laws of the United States and by the laws of the State of Missouri, without regard to conflicts of law principles. You consent and agree to the personal jurisdiction of, and that venue is proper in, the state courts of Greene County, Missouri, and waive any objection to such jurisdiction or venue. You agree that no cause of action shall be initiated, nor maintained, in any jurisdiction other than the state courts of Greene County, Missouri. In the event of any controversy or dispute between Romine Enterprises, LLC and you arising out of or in connection with your use of the Site, the parties shall attempt, promptly and in good faith, to resolve any such dispute. If we are unable to resolve any such dispute within a reasonable time (not to exceed thirty (30) days), then the parties shall be free to pursue any right or remedy available to them under applicable law.</p>

			<p>Romine Enterprises, LLC administers and operates the Site from its location in the State of Missouri, USA. Although the Site is accessible worldwide, not all features, products or services discussed, referenced, provided or offered through or on the Site are available to all persons or in all geographic locations, or appropriate or available for use outside the United States. Romine Enterprises, LLC reserves the right to limit, in its sole discretion, the provision and quantity of any product or service to any person or geographic area. Any offer for any feature, product or service made on the Site is void where prohibited. If you choose to access the Site from outside the United States, you do so on your own initiative and you are solely responsible for complying with applicable local laws.</p>

			<p>You may not use or export or re-export any Content or any copy or adaptation of such Content, or any product or service offered on the Site, in violation of any applicable laws or regulations.</p>

			<p>If any of the provisions of these Terms of Use, or any relevant terms and conditions, policies and notices, are held by a court or other tribunal of competent jurisdiction, whether due to being void, invalidity, illegality, unlawfulness or for any reason whatever, shall, in such jurisdiction only and only to the extent that it is so unenforceable, be treated as void and the remaining provisions of any relevant terms and conditions, policies and notices shall remain in full force and effect. These Terms of Use constitute the entire agreement between you and Romine Enterprises, LLC with regard to your use of the Site, and any and all other written or oral agreements or understandings previously existing between you and Romine Enterprises, LLC with respect to such use are hereby superseded and cancelled. Romine Enterprises, LLC will not accept any counter-offers to these Terms of Use, and all such offers are hereby categorically rejected. Romine Enterprises, LLC’s failure to insist on or enforce strict performance of these Terms of Use shall not be construed as a waiver by Romine Enterprises, LLC of any provision or any right it has to enforce these Terms of Use, nor shall any course of conduct between Romine Enterprises, LLC and you or any other party be deemed to modify any provision of these Terms of Use. These Terms of Use shall not be interpreted or construed to confer any rights or remedies on or to any third parties.</p>

			<p>The Romine Enterprises, LLC sells and ships products to end-user customers only. You may not purchase products on www.color-my-i.com for resale.</p>

			<p>Once we receive your order, we’ll provide you with an email order confirmation. Your receipt of an order confirmation, however, does not signify Romine Enterprises, LLC’s acceptance of your order, nor does it constitute confirmation of our offer to sell; we are simply confirming that we received your order. Romine Enterprises, LLC reserves the right at any time after receiving your order to accept or decline your order for any reason. If Romine Enterprises, LLC cancels an order after you have already been billed, Romine Enterprises, LLC will refund the billed amount.</p>

			<p>With regards to pricing, Romine Enterprises, LLC reserves the right to change prices for products displayed at/on the www.color-my-i.com at any time, and to correct pricing errors that may inadvertently occur.</p>

			<p>BY PURCHASING ANY ITEMS OR SERVICES, YOU AGREE TO THESE TERMS; IF YOU DO NOT AGREE, DO NOT PURCHASE ANY ITEMS OR SERVICES. THESE TERMS ARE AN INTEGRAL AND MATERIAL PART OF THE PURCHASE CONTRACT AND TH E BARGAIN BETWEEN THE PARTIES.</p>

			<p>ALL ITEMS AND SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE", WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND ROMINE ENTERPRISES, LLC AND ITS AGENTS AND LICENSEES HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THE ITEMS AND SERVICES, EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, WORKMANLIKE QUALITY, AND NON-INFRINGEMENT OF THIRD PARTY RIGHTS.</p>

			<p>ROMINE ENTERPRISES, LLC DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE SOFTWARE AND SERVICES, THAT THE FUNCTIONS CONTAINED IN OR SERVICES PERFORMED BY THE ITEM WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE ITEM AND SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, THAT ANY SERVICE WILL CONTINUE TO BE MADE AVAILABLE, OR THAT DEFECTS IN THE ITEM OR SERVICES WILL BE CORRECTED.</p>

			<p>TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY ROMINE ENTERPRISES, LLC OR ITS AGENTS SHALL CREATE A WARRANTY. SHOULD ANY ITEM BE DEFECTIVE, UNSATISFACTORY, OR BECOME DAMAGED YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.</p>

			<p>TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, IN NO EVENT SHALL ROMINE ENTERPRISES, LLC BE LIABLE FOR PERSONAL INJURY, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, CORRUPTION OR LOSS OF DATA, FAILURE TO TRANSMIT OR RECEIVE ANY DATA, BUSINESS INTERRUPTION OR ANY OTHER DAMAGES OR LOSSES, INCLUDING PERSONAL INJURY, OR ANY OTHER CAUSE OF ACTION ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE ITEM, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT OR OTHERWISE) AND EVEN IF ROMINE ENTERPRISES, LLC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>

			<p>You agree that all purchases or orders, requests for or the rendition of services, including all disputes arising therefrom or in any way pertaining thereto, will be governed by the laws of the United States and the laws of the State of Missouri, without regard to conflicts of law principles. You consent and agree to the personal jurisdiction of, and that venue is proper in, the state courts of Greene County, Missouri, and waive any objection to such jurisdiction or venue. You agree that all contracts related to your purchase, order, or request for services are entered into, and finally executed, in Greene County, Missouri. You agree that no cause of action shall be initiated, nor maintained, in any jurisdiction other than the state courts of Greene County, Missouri. In the event of any controversy or dispute between Romine Enterprises, LLC and you arising out of or in connection with your use of the Site, the parties shall attempt, promptly and in good faith, to resolve any such dispute. If we are unable to resolve any such dispute within a reasonable time (not to exceed thirty (30) days), then the parties shall be free to pursue any right or remedy available to them under applicable law.</p>

			<p>You understand and agree that Romine Enterprises, LLC will not be responsible for mailing mistakes, customer typos, or damages incurred to any items during shipping or transit. Romine Enterprises, LLC will not be held liable for any damage to your item or the data stored on it, including but not limited to damage caused during shipping, transit, or in the course of any repair or modification.</p>

			<p>You understand and agree that Romine Enterprises, LLC will not accept returns or exchanges of purchased items or services for any reason. If for any reason and by any means, whether intentional or accidental, you become possessed of Romine Enterprises, LLC’s property without Romine Enterprises, LLC receiving and being permitted to retain adequate consideration therefore, you are obligated to return such property.</p>

			<p>If Romine Enterprises, LLC does take any legal action against you pertaining to or arising from any purchase, order, request for or the rendition of services, whether contractual or otherwise, Romine Enterprises, LLC will be entitled to recover from you, and you agree to pay, all reasonable attorneys’ fees and costs incurred by Romine Enterprises, LLC in preparation for or as a result of such action, in addition to any other relief granted to Romine Enterprises, LLC, which specifically includes but is not limited to costs incurred in identifying, locating, or contacting you in an effort to resolve a dispute prior to the initiation of any action, even if no action results.</p>
		</div>

		<?php
			include "sidebar.php";
		?>

	</div><!-- /.row -->

<?php
include "footer.php";
?>